-- ============================================================
-- Seed Data: Katalog Produk Awal (15 Produk Populer & Terverifikasi BPOM)
-- ============================================================

INSERT INTO public.products (
  name,
  brand,
  category,
  key_ingredients,
  skin_type_fit,
  price_estimate,
  marketplace_url,
  image_url,
  listing_type,
  sponsor_weight,
  is_active
) VALUES
(
  'Skintific 5X Ceramide Barrier Repair Moisture Gel',
  'Skintific',
  'Moisturizer',
  ARRAY['Ceramide', 'Hyaluronic Acid', 'Centella Asiatica', 'Panthenol'],
  ARRAY['dry', 'sensitive', 'normal', 'combination'],
  'Rp 120.000 - 140.000',
  'https://shopee.co.id',
  NULL,
  'organic',
  0,
  true
),
(
  'Skintific 2% Salicylic Acid Anti Acne Serum',
  'Skintific',
  'Serum',
  ARRAY['Salicylic Acid', 'Niacinamide', 'Ceramide', 'Centella Asiatica', 'Zinc PCA'],
  ARRAY['oily', 'combination', 'sensitive'],
  'Rp 115.000 - 135.000',
  'https://shopee.co.id',
  NULL,
  'organic',
  0,
  true
),
(
  'Somethinc 10% Niacinamide + Moisture Sabi Beet Max Brightening Serum',
  'Somethinc',
  'Serum',
  ARRAY['Niacinamide', 'Centella Asiatica', 'Zinc PCA'],
  ARRAY['oily', 'combination', 'normal'],
  'Rp 115.000 - 130.000',
  'https://shopee.co.id',
  NULL,
  'organic',
  0,
  true
),
(
  'Somethinc 2% BHA Salicylic Acid Liquid Perfector',
  'Somethinc',
  'Exfoliant',
  ARRAY['Salicylic Acid', 'Zinc PCA', 'Tea Tree'],
  ARRAY['oily', 'combination'],
  'Rp 110.000 - 125.000',
  'https://shopee.co.id',
  NULL,
  'organic',
  0,
  true
),
(
  'Somethinc Granactive Retinoid 2% Emulsion',
  'Somethinc',
  'Serum',
  ARRAY['Retinol', 'Granactive Retinoid', 'Hyaluronic Acid', 'Ceramide'],
  ARRAY['normal', 'combination', 'dry', 'oily'],
  'Rp 150.000 - 175.000',
  'https://shopee.co.id',
  NULL,
  'organic',
  0,
  true
),
(
  'Avoskin Miraculous Refining Toner',
  'Avoskin',
  'Toner',
  ARRAY['AHA', 'BHA', 'Salicylic Acid', 'Niacinamide', 'Tea Tree'],
  ARRAY['oily', 'combination'],
  'Rp 160.000 - 180.000',
  'https://shopee.co.id',
  NULL,
  'organic',
  0,
  true
),
(
  'Avoskin Your Skin Bae Vitamin C 3% + Niacinamide 2% Serum',
  'Avoskin',
  'Serum',
  ARRAY['Vitamin C', 'Niacinamide', 'Hyaluronic Acid'],
  ARRAY['normal', 'combination', 'dry'],
  'Rp 135.000 - 150.000',
  'https://shopee.co.id',
  NULL,
  'organic',
  0,
  true
),
(
  'The Originote Hyalucera Moisturizer Gel',
  'The Originote',
  'Moisturizer',
  ARRAY['Hyaluronic Acid', 'Ceramide', 'Centella Asiatica'],
  ARRAY['dry', 'normal', 'combination', 'oily'],
  'Rp 42.000 - 55.000',
  'https://shopee.co.id',
  NULL,
  'organic',
  0,
  true
),
(
  'The Originote Cica-B5 Soothing Cleanser',
  'The Originote',
  'Cleanser',
  ARRAY['Centella Asiatica', 'Panthenol', 'Salicylic Acid'],
  ARRAY['sensitive', 'oily', 'combination'],
  'Rp 38.000 - 45.000',
  'https://shopee.co.id',
  NULL,
  'organic',
  0,
  true
),
(
  'Glad2Glow Centella Allantoin Soothing Gel Moisturizer',
  'Glad2Glow',
  'Moisturizer',
  ARRAY['Centella Asiatica', 'Allantoin', 'Panthenol'],
  ARRAY['oily', 'sensitive', 'combination'],
  'Rp 39.000 - 49.000',
  'https://shopee.co.id',
  NULL,
  'organic',
  0,
  true
),
(
  'Glad2Glow Mugwort Salicylic Acid Acne Clay Stick',
  'Glad2Glow',
  'Mask',
  ARRAY['Salicylic Acid', 'Mugwort', 'Centella Asiatica', 'Niacinamide'],
  ARRAY['oily', 'combination'],
  'Rp 39.000 - 49.000',
  'https://shopee.co.id',
  NULL,
  'organic',
  0,
  true
),
(
  'Azarine Hydrasoothe Sunscreen Gel SPF45 PA++++',
  'Azarine',
  'Sunscreen',
  ARRAY['Hyaluronic Acid', 'Centella Asiatica', 'Niacinamide'],
  ARRAY['oily', 'combination', 'sensitive', 'normal'],
  'Rp 55.000 - 65.000',
  'https://shopee.co.id',
  NULL,
  'organic',
  0,
  true
),
(
  'Cosrx Low pH Good Morning Gel Cleanser',
  'Cosrx',
  'Cleanser',
  ARRAY['Tea Tree', 'Betaine Salicylate', 'Salicylic Acid'],
  ARRAY['oily', 'sensitive', 'combination'],
  'Rp 95.000 - 120.000',
  'https://shopee.co.id',
  NULL,
  'organic',
  0,
  true
),
(
  'Cosrx Advanced Snail 96 Mucin Power Essence',
  'Cosrx',
  'Toner',
  ARRAY['Snail Mucin', 'Hyaluronic Acid', 'Panthenol', 'Allantoin'],
  ARRAY['dry', 'sensitive', 'normal', 'combination'],
  'Rp 170.000 - 210.000',
  'https://shopee.co.id',
  NULL,
  'organic',
  0,
  true
),
(
  'Wardah UV Shield Essential Gel Sunscreen SPF 35 PA+++',
  'Wardah',
  'Sunscreen',
  ARRAY['Vitamin C', 'Vitamin E', 'Panthenol', 'Niacinamide'],
  ARRAY['normal', 'dry', 'combination'],
  'Rp 35.000 - 42.000',
  'https://shopee.co.id',
  NULL,
  'organic',
  0,
  true
);
